import { useEffect, useMemo, useState } from 'react'

import './App.css'
import { fetchCourses, type Course } from './api'
import { ChatPanel } from './components/ChatPanel'
import { CourseGrid } from './components/CourseGrid'

const ALL = 'All'

export default function App() {
  const [courses, setCourses] = useState<Course[]>([])
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState(ALL)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Debounce so every keystroke doesn't hit the API.
  useEffect(() => {
    const controller = new AbortController()
    const timer = setTimeout(() => {
      setLoading(true)
      fetchCourses(search, controller.signal)
        .then((res) => {
          setCourses(res.courses)
          setError(null)
        })
        .catch((err: Error) => {
          if (err.name !== 'AbortError') setError(err.message)
        })
        .finally(() => setLoading(false))
    }, 250)

    return () => {
      clearTimeout(timer)
      controller.abort()
    }
  }, [search])

  const categories = useMemo(() => {
    const found = new Set(courses.map((c) => c['Course Category']).filter(Boolean))
    return [ALL, ...[...found].sort()]
  }, [courses])

  const visible = useMemo(
    () =>
      category === ALL
        ? courses
        : courses.filter((c) => c['Course Category'] === category),
    [courses, category],
  )

  return (
    <div className="app">
      <header className="masthead">
        <div className="masthead__inner">
          <div className="masthead__brand">
            <span className="masthead__mark">Y</span>
            <div>
              <h1>Yale SOM Course Explorer</h1>
              <p>Browse the catalog, or ask the assistant.</p>
            </div>
          </div>
          <span className="masthead__count">
            {loading ? 'Loading…' : `${visible.length} courses`}
          </span>
        </div>
      </header>

      <main className="layout">
        <section className="catalog" aria-label="Course catalog">
          <div className="controls">
            <input
              className="search"
              type="search"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by title, number, faculty, topic…"
              aria-label="Search courses"
            />
            <div className="filters" role="group" aria-label="Filter by category">
              {categories.map((cat) => (
                <button
                  key={cat}
                  type="button"
                  className={`chip${cat === category ? ' chip--on' : ''}`}
                  onClick={() => setCategory(cat)}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          <CourseGrid courses={visible} loading={loading} error={error} />
        </section>

        <aside className="sidebar">
          <ChatPanel />
        </aside>
      </main>

      <footer className="footer">
        Course data from <code>yale_som_classes.json</code> · answers generated by an AI
        agent — verify before you bid.
      </footer>
    </div>
  )
}
